const lang = {
  en: {
    trending: "Trending",
    popular: "Popular",
    movies: "Movies",
    tvShows: "Tv Shows",
    people: "People",
    searchPlaceholder: "Search for movies, TV shows, or people...",
    playTrailer: "Play trailer",
    stopTrailer: "Stop trailer",
    trailerNA: "Trailer Not Available",
    gptBtn: "GPT Search",
    filter: "Filter",
    home: "Home",
    lightMode: "Light Mode",
    saved: "Saved",
    logOut: "Log Out",
    hi: "Hi",
    topCast: "Top Cast",
    similar: "Similar",
    recommendations: "Recommendations",
    seasons: "Seasons",
    nowStreaming: "Now Streaming",
    watchNow: "Watch Now",
    userScore: "User Score",
    overView: "Overview",
    gptSearchPlaceholder: "Discover your next binge-worthy show...",
    search: "Search",
  },
  hindi: {
    trending: "ट्रेंडिंग",
    popular: "ट्लोकप्रिय",
    movies: "चलचित्र",
    tvShows: "टीवी शो",
    people: "लोग",
    searchPlaceholder: "फ़िल्में, टीवी शो या लोगों को खोजें...",
    playTrailer: "ट्रेलर चलाएं",
    stopTrailer: "ट्रेलर रोकें",
    trailerNA: "ट्रेलर उपलब्ध नहीं है",
    gptBtn: "जीपीटी खोज",
    filter: "फ़िल्टर",
    home: "होम",
    lightMode: "लाइट मोड",
    saved: "सहेजा गया",
    logOut: "लॉग आउट",
    hi: "नमस्ते",
    topCast: "मुख्य कलाकार",
    similar: "समान",
    recommendations: "सिफारिशें ",
    seasons: "सत्र",
    nowStreaming: "अब स्ट्रीमिंग हो रहा है",
    watchNow: "अभी देखें",
    userScore: "उपयोगकर्ता स्कोर",
    overView: "संक्षिप्त विवरण",
    gptSearchPlaceholder: "अपना अगला दिलचस्प शो खोजें...",
    search: "खोजें",
  },
  spanish: {
    trending: "Tendencia",
    popular: "Popular",
    movies: "Cine",
    tvShows: "Programas de televisión",
    people: "Gente",
    searchPlaceholder:
      "Busque películas, programas de televisión o personas...",
    playTrailer: "Reproducir tráiler",
    stopTrailer: "Detener remolque",
    trailerNA: "Tráiler no disponible",
    gptBtn: "Búsqueda GPT",
    filter: "Filtrar",
    home: "Home",
    lightMode: "Modo claro",
    saved: "Guardado",
    logOut: "Cerrar sesión",
    hi: "Hola",
    topCast: "Elenco Principal",
    similar: "Similar",
    recommendations: "Recomendaciones",
    seasons: "Temporada",
    nowStreaming: "Ahora en Streaming",
    watchNow: "Ver Ahora",
    userScore: "Puntuación del Usuario",
    overView: "Resumen",
    gptSearchPlaceholder: "Descubre tu próximo programa adictivo...",
    search: "Buscar",
  },
  telugu: {
    trending: "ట్రెండింగ్‌లో ఉంది",
    popular: "జనాదరణ పొందినది",
    movies: "సినిమాలు",
    tvShows: "టీవీ షోలు",
    people: "ప్రజలు",
    searchPlaceholder:
      "చలనచిత్రాలు, టీవీ కార్యక్రమాలు లేదా వ్యక్తుల కోసం శోధించండి...",
    playTrailer: "ట్రైలర్ ప్లే చేయండి",
    stopTrailer: "ట్రైలర్ ఆపు",
    trailerNA: "ట్రైలర్ అందుబాటులో లేదు",
    gptBtn: "GPT శోధన",
    filter: "ఫిల్టర్ చేయండి",
    home: "హోమ్",
    lightMode: "లైట్ మోడ్",
    saved: "సేవ్ చేయబడింది",
    logOut: "లాగ్ అవుట్",
    hi: "హలో",
    topCast: "ప్రధాన నటులు",
    similar: "సమానమైన ",
    recommendations: "సిఫారసులు",
    seasons: "సీజన్",
    nowStreaming: "ఇప్పుడు స్ట్రీమింగ్‌లో ఉంది",
    watchNow: "ఇప్పుడు చూడండి",
    userScore: "వినియోగదారు స్కోరు",
    overView: "అవలోకనం",
    gptSearchPlaceholder: "మీ తదుపరి బింజ్-వర్ధీ షోను కనుగొనండి...",
    search: "వెతకండి",
  },
};

export default lang;
